### ISSUE TITLE
Version auto-detection v3.0-RC

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs-validator#113]
It seems the validator is having difficulties with auto-detecting v3.0. 

I was testing with these feeds:
- https://data-sharing.tier-services.io/tier_paris/gbfs/3.0
- https://data.rideflamingo.com/gbfs/3/wellington/gbfs.json

**Comment by PierrickP** [comment]
Hello @josee-sabourin 
Currently, the validation only valid v3.0-**RC**

You can force the version with "v3.0-RC"
![image](https://github.com/MobilityData/gbfs-validator/assets/1214544/92c9a7c9-b7cc-4785-b2fa-d102a441469b)

(The validation pass with the Tier feed but actually, it's totally wrong :( )

**Comment by josee-sabourin** [comment]
Gotcha, I assume this isn't worth fixing since the RC will be deprecated once the version is official. 

Re: Tier I have contacted them about the issues

**Comment by PierrickP** [comment]
Yes, when the version is released, we update the validation directly accept the version

In addition, this https://github.com/MobilityData/gbfs-json-schema/pull/92 fix schema to correctly validate this error

**Comment by richfab** [comment]
Fixed by https://github.com/MobilityData/gbfs-json-schema/pull/92
