### ISSUE TITLE
Add `API Key` authentification method

### ISSUE THREAD

**Issue by richfab** [MobilityData/gbfs-validator#117]
Some private feeds require an API Key to be fetched.
It would be useful to add the `API Key` authentification method to validate such feeds.

Before | After
-- | --
<img width="1422" alt="image" src="https://github.com/MobilityData/gbfs-validator/assets/2423604/06eefbdb-fe59-4d01-b193-5325b155719f"> | <img width="1450" alt="image" src="https://github.com/MobilityData/gbfs-validator/assets/2423604/967f8506-3e7f-470a-838a-8e338943c1c8">

**Comment by testower** [comment]
What exactly does «API Key» mean in this context?

**Comment by richfab** [comment]
> What exactly does «API Key» mean in this context?

I was thinking `API Key` in the context of a unique identifier used to authenticate the client to the server. The API Key is passed in the request header, such as `X-API-KEY: key`. Thoughts?

**Comment by testower** [comment]
I think the header name should be configurable

**Comment by richfab** [comment]
> I think the header name should be configurable, since “x-api-key” is non-standard, and it may vary what people use in the field.

Good point. I made the header name configurable. Thank you!
