### ISSUE TITLE
Response code 500 on Link.city feeds

### ISSUE THREAD

**Issue by richfab** [MobilityData/gbfs-validator#122]
## Observed
Currently, the validator does not work on some Link.city feeds (I tested 5 different Link systems from [systems.csv](https://github.com/MobilityData/gbfs/blob/master/systems.csv) and they all returned the same error message).

ie: https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fmds.linkyour.city%2Fgbfs%2Fus_tx_dallas%2Fgbfs.json
<img width="1480" alt="image" src="https://github.com/MobilityData/gbfs-validator/assets/2423604/b56a0a94-4de6-4808-9990-4dc390810800">
Feed: https://mds.linkyour.city/gbfs/us_tx_dallas/gbfs.json

## Expected
The validation report should be displayed.

## Investigation
In debug mode, we see that the response for the URL https://mds.linkyour.city/gbfs/us_tx_dallas/gbfs.json is code 500. I would need help to continue the investigation please. Thank you!

https://github.com/MobilityData/gbfs-validator/blob/master/gbfs-validator/gbfs.js#L282

<img width="757" alt="image" src="https://github.com/MobilityData/gbfs-validator/assets/2423604/314a14e6-e29b-444b-b191-659188346ad9">

**Comment by josee-sabourin** [comment]
Check out #90, maybe will help!

**Comment by richfab** [comment]
Duplicate of https://github.com/MobilityData/gbfs-validator/issues/90
