### ISSUE TITLE
Missing required files and API results

### ISSUE THREAD

**Issue by AntoineAugusti** [MobilityData/gbfs-validator#170]
Follow up of #127 and the fix introduced in #169 

### What is the issue and _why_ is it an issue?

When a file is missing but required, the API now says 

```json
"summary": {
  "errorsCount": 0,
  "hasErrors": true
}
```

![image](https://github.com/MobilityData/gbfs-validator/assets/295709/eae4ab8f-a61d-4b45-a19b-75b79500eeea)

which seems unexpected.

[Example](https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fapi.prod.partners-fs37hd8.zoov.eu%2Fgbfs%2F2.2%2Fbrest%2Fen%2Fgbfs.json%3F%26key%3DOGNhZDNjMDQtYTA0Yi00NzU2LWE0MTItOGJlYzE1Y2E4NGEx)

## Proposed fix

`errorsCount` should be the sum of GBFS errors + the number of missing required files

**Comment by jcpitre** [comment]
Some work has been done on a similar issue: https://github.com/MobilityData/gbfs-validator/pull/169

**Comment by AntoineAugusti** [comment]
Thank you for the fix @Alessandro100! It works: [example](https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fapi.prod.partners-fs37hd8.zoov.eu%2Fgbfs%2F2.2%2Fbrest%2Fen%2Fgbfs.json%3F%26key%3DOGNhZDNjMDQtYTA0Yi00NzU2LWE0MTItOGJlYzE1Y2E4NGEx)
