### ISSUE TITLE
Support v3.0

### ISSUE THREAD

**Issue by richfab** [MobilityData/gbfs-validator#180]
## Context
v3.0 became the official version on April 11, 2024 (see [release notes](https://github.com/MobilityData/gbfs/releases/tag/v3.0)).

The validator needs to be updated to support v3.0.

## To do
- [x] Add the new [v3.0 JSON Schema](https://github.com/MobilityData/gbfs-json-schema/tree/master/v3.0) to `gbfs-validator/versions/schemas`.
- [x] Remove the v3.0-RC and v3.0-RC2 JSON Schemas from `gbfs-validator/versions/schemas`.
- [x] Support validation of v3.0 feeds (one example feed [here](https://api.dev.entur.io/mobility/v2/gbfs/v3beta/getaroundstavanger/gbfs)).
- [x] Remove support and mentions of v3.0-RC and v3.0-RC2.
- [x] Remove `reservation_price_per_min` and `reservation_price_flat_rate` from the fixtures `gbfs-validator/__test__/fixtures/v3.0-RC2/exaustive.js` because https://github.com/MobilityData/gbfs/pull/457 was withdrawned from v3.0.

**Comment by Alessandro100** [comment]
@richfab the feed you linked https://api.dev.entur.io/mobility/v2/gbfs/v3beta/getaroundstavanger/gbfs uses v3.0-RC2. Do you know if someone is already on v3.0?

**Comment by richfab** [comment]
> @richfab the feed you linked https://api.dev.entur.io/mobility/v2/gbfs/v3beta/getaroundstavanger/gbfs uses v3.0-RC2. Do you know if someone is already on v3.0?

You may use https://data-sharing.tier-services.io/tier_paris/gbfs/3.0/ from TIER.

**Comment by testower** [comment]
Seems like this can be closed @richfab @Alessandro100 ?

**Comment by richfab** [comment]
Indeed! Thank @testower. Closing now ✅
