### ISSUE TITLE
Link the gbfs-validator directly with the JSON Schemas

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/gbfs-validator#60]
The JSON Schemas have been updated and the organisation of the GBFS releases are now [per folder](https://github.com/MobilityData/gbfs-json-schema).

The gbfs-validator should be directly using the schemas from the JSON Schema repository in order to avoid maintaining them twice.

**Comment by PierrickP** [comment]
closed with https://github.com/MobilityData/gbfs-validator/pull/62
