### ISSUE TITLE
Timezone not properly validated

### ISSUE THREAD

**Issue by mikael-epigram** [MobilityData/gbfs-validator#76]
Timezone as defined in https://github.com/NABSA/gbfs/blob/v2.3/gbfs.md#field-types
states:
```
Timezone - TZ timezone from the https://www.iana.org/time-zones. Timezone names never contain the space character but MAY contain an underscore. Refer to https://en.wikipedia.org/wiki/List_of_tz_zones for a list of valid values. Example: Asia/Tokyo, America/Los_Angeles or Africa/Cairo.
```
The schema in system_information.json seems to not make any requirements of the field:

```
"timezone": {
    "description": "The time zone where the system is located.",
    "type": "string"
},
```
This does not seem to comply to the gbfs standard

**Comment by leonardehrenfried** [comment]
Examples of invalid time zones:

- https://gbfs.hopr.city/api/gbfs/20/system_information
- https://gbfs.spin.pm/api/gbfs/v1/atlanta/system_information

So it's more common than I hoped.

**Comment by isabelle-dr** [comment]
@PierrickP this has been updated on the Json Schema 😊

**Comment by PierrickP** [comment]
#82 :tada:
