### ISSUE TITLE
Impossible de validate Salavador pbsc

### ISSUE THREAD

**Issue by PierrickP** [MobilityData/gbfs-validator#84]
Url: `https://salvador.publicbikesystem.net/operation/customer/gbfs/v2/gbfs.json`

Timeout on prod, 
In local, the GBFS file is invalid (2 wrong filename) and no file are founded

**Comment by josee-sabourin** [comment]
This seems to have solved itself, at least on my end. Can you check if this is the case for you?

**Comment by PierrickP** [comment]
Yes, fixes itself.
Sometime, it's just because they block "datacenter" IPs
