### ISSUE TITLE
Proposal: validate GBFS version 2.1-RC

### ISSUE THREAD

**Issue by Manu1400** [MobilityData/gbfs-validator#87]
## case
https://gbfs.beryl.cc/v2/Cornwall/gbfs.json is a 2.1-RC feed.

[online validation](https://gbfs-validator.netlify.app/?url=https%3A%2F%2Fgbfs.beryl.cc%2Fv2%2FCornwall%2Fgbfs.json) return :
> Detected version 2.1-RC and validate with [2.0](https://github.com/NABSA/gbfs/blob/v2.0/gbfs.md)
> Invalid GBFS feed
> 87 errors

## documentation
https://github.com/MobilityData/gbfs/releases/tag/v2.1-RC
> Released May 22, 2020.
> MINOR release - Backwards compatible with v2.0
> New features:
> * Add vehicle type definitions
> * Add geofencing, virtual station, and dockless support

**Comment by josee-sabourin** [comment]
Hello and welcome! 

Best practice is to only use an RC feed if you are an early adopter of a feature and there is no official version yet. Once all the features in an RC are implemented, it becomes an official version. Bearing that in mind we don't validate release candidates if an official corresponding version exists. I would encourage Beryl to use v2.1 (or even better our latest version, v2.3!). 

Hope that helps!

**Comment by richfab** [comment]
This v2.1-RC feed can now be validated by selecting version v2.1 in the dropdown. Thank you!

<img width="1342" alt="Screenshot 2024-01-17 at 11 01 26" src="https://github.com/MobilityData/gbfs-validator/assets/2423604/12f4ef81-c853-4f84-a3df-43ef53a42cc9">

Link: https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fgbfs.beryl.cc%2Fv2%2FCornwall%2Fgbfs.json
