### ISSUE TITLE
Validate for both lowercase and uppercase enums?

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs-validator#88]
The spec states that `Enum values SHOULD be lowercase.`. As a reminder the spec uses [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119) for requirement level language. 

The validator is flagging errors in datasets that use uppercase enum values. Example [here](https://gbfs-validator.netlify.app/?url=https%3A%2F%2Fsalvador.publicbikesystem.net%2Foperation%2Fcustomer%2Fgbfs%2Fv2%2Fgbfs.json).

Because the lowercase is recommended and _not required_ (and effectively a best practice), should the validator consider feeds using uppercase as valid? This opens the question on whether the validator should validate for best practices, or just the specification.

**Comment by testower** [comment]
Wow, I actually didn't realize the spec said SHOULD on this matter. This makes it quite inconvenient for deserializing. Any chance we could propose to change this to MUST for 3.0?

**Comment by josee-sabourin** [comment]
For anyone who is not following over on the GBFS repository - the PR addressing this change is [open for a vote here](https://github.com/MobilityData/gbfs/pull/474).

**Comment by josee-sabourin** [comment]
Closing this as the PR on the specification has passed!
