### ISSUE TITLE
Unable to validate Link Granada

### ISSUE THREAD

**Issue by josee-sabourin** [MobilityData/gbfs-validator#90]
Error when validating https://mds.linkyour.city/gbfs/es_granada/gbfs.json. 
"Sorry, this version is not yet implemented or not detectable !", even when specifying the version, same error message.

**Comment by PierrickP** [comment]
They block the default Got User-Agent

```bash
curl -I -H 'User-Agent: got (https://github.com/sindresorhus/got)' https://mds.linkyour.city/gbfs/es_granada/gbfs.json
```
return **500**
But 

```
curl -I https://mds.linkyour.city/gbfs/es_granada/gbfs.json
```
Works

We could change our user-agent to allow us to be properly identified (eg: `gbfs-validator (https://github.com/MobilityData/gbfs-validator)`)
It is not bullet proof. They can still block it.

**Comment by josee-sabourin** [comment]
@ezmckinn can you provide any insight here? Would Superpedestrian prefer a more identifiable user-agent?

**Comment by ezmckinn** [comment]
Hi @josee-sabourin and @richfab  — thanks for raising this. I actually have struggled to use the GBFS validator in the past, for our own spot-checking, so we'll be glad to work on this. I will file a bug ticket internally and provide on updates on this thread as the fix is processed.

**Comment by davidgamez** [comment]
For consistency between MobilityData validators, let's use a similar pattern described [here](https://github.com/MobilityData/gtfs-validator/issues/1562#issuecomment-1885377640). In this case user agent should be: `User-Agent: MobilityData GBFS-Validator/{VALIDATOR_VERSION} ({NODE_VERSION})`

**Comment by Alessandro100** [comment]
With the latest version bump it should be working now 
fixing pr: https://github.com/MobilityData/gbfs-validator/pull/182

![Screenshot 2024-04-17 at 11 11 32](https://github.com/MobilityData/gbfs-validator/assets/18631060/1f7a2f6a-abf2-4600-9536-c6c3ecf7d927)
